---
- name: Upgrade all packages
  yum:
    name: '*'
    state: latest
- name: Install required packages via yum
  yum:
    name:
      - vim
      - bc
      - python3-setuptools
      - python3-pkg-resources
    state: latest

- name: Install required packages via pip
  pip:
    name:
      - jmespath
    state: latest
    