---
- name: Upgrade all packages
  yum:
    name: '*'
    state: latest

- name: Install required packages via yum
  yum:
    name:
      - vim
      - bc
      - gcc 
      - zlib-devel 
      - bzip2 
      - bzip2-devel 
      - readline-devel 
      - sqlite 
      - sqlite-devel
      - epel-release
      - openssl11
      - openssl11-libs
      - openssl11-devel 
      - tk-devel 
      - libffi-devel 
      - xz-devel
      - wget
    state: latest

- name: Add openssl11 headers to a single location
  block:
    - name: Create an openssl11 dir in /usr/local
      file:
        path: /usr/local/openssl11
        state: directory
    - name: Link requisite libraries
      file:
        src: /usr/lib64/openssl11
        dest: /usr/local/openssl/lib
        state: link
    - name: Link requisite headers
      file:
        src: /usr/include/openssl11
        dest: /usr/local/openssl/include
        state: link

- name: Configure pyenv
  block:
    - name: install pyenv
      shell: |
        curl https://pyenv.run | bash \
        export PYENV_ROOT="$HOME/.pyenv" \
        command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH" \
        eval "$(pyenv init -)"
    - name: install Python 3
      shell: |
        CONFIGURE_OPTS="--with-openssl=/usr/local/openssl11" pyenv install -v 3.10.5 \
        pyenv global 3.10.5


- name: Install required packages via pip
  pip:
    name:
      - jmespath
    state: latest
  tags:
    - pip-task
    