on: [push]

jobs:
  xccdf-validate:
    runs-on: ubuntu-latest
    name: Validate xccdf
    steps:
      - uses: actions/checkout@master

      - name: Check for an update
        uses: mitre/inspec-profile-update-action@main
        with:
          profile: '2e257e0f-10c8-4972-8873-870cfa0caf30'